### ISSUE TITLE
Missing aaeon modules

### ISSUE THREAD

**Issue by 53845714nF** [arighi/annotations#3]
I don't know if this is the right place, but I have the following problem.

I use this to build Kernel (linux-source-6.5.0) on Ubuntu Mantic:
```bash
debian/rules clean
debian/rules updateconfigs

debian/rules binary-headers binary-server \
    do_zfs=false \
    do_dkms_nvidia=false \
    do_dkms_nvidia_server=false \
        skipabi=true \
        skipmodule=true \
        skipretpoline=true
```

It builds the kernel but cannot build Debian packages from it. So I get this Error: 
There is no aaeon stuff config in my annotations.
```bash
debian/scripts/checks/module-check "generic" \
        "/source/build/kernel/debian.master/abi/amd64" "/source/build/kernel/debian.master/__abi.current/amd64" 
II: Checking modules for generic...
    Reading modules to ignore...read 11 modules.
    Reading new modules...read 6659 modules.
    Reading old modules...read 6665 modules.
II: Checking for modules changes...
    MISS : gpio-aaeon
    MISS : hwmon-aaeon
    MISS : leds-aaeon
    MISS : mfd-aaeon
    MISS : spl (ignored)
    MISS : zfs (ignored)
EE: Missing modules
```

If you want me to provide any other information about the error, please let me know.

**Comment by arighi** [comment]
This is not strictly related to annotations, the ABI check tells you that you're going to drop these modules if you recompile the kernel with this config, but that's probably fine.

If you don't care about them you can completely ignore the ABI checks as following:
```
$ for d in `ls -d debian.master/abi/*/`; do echo 1 > $d/ignore; echo 1 > $d/ignore.modules; echo 1 > $d/ignore.retpoline; done
```

In recent kernels (in 24.04) we've removed the ABI checks, so you won't see this issue with newer kernels.

**Comment by 53845714nF** [comment]
This is one of my side projects, might not be able to take care of it during the week. I will get back to you as soon as I have time.

**Comment by 53845714nF** [comment]
Unfortunately, I don't have time to continue this, so I'm closing the issue.
